# Generated by Django 4.2.1 on 2023-05-23 16:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0002_alter_boardad_contentboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardad',
            name='contentBoard',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
